import { Injectable } from '@angular/core';
import {Interval, Job, JobStatus, Price, MaterialId} from '../../model/Subscription';

@Injectable({
  providedIn: 'root'
})
export class JobsService {

  constructor() { }

  public find(): Job[] {
    const jobs = [];
    let job = new Job();
    job.type = 'sammelsack-ch-recycling';
    job.description = 'Sammelsack';
    job.first_start_date = new Date().toISOString();
    job.last_done_date = new Date().toISOString();
    job.status = new JobStatus();
    job.status.state = 0;
    job.price = new Price();
    job.price.value_per_kg = 2;
    job.price.value = 0;
    job.material_id = MaterialId.SAMMELSACK_CH;
    job.image_name = '' + job.material_id.valueOf() + '.svg';
    job.is_selected = false;
    job.sammelstellen = [];
    jobs.push(job);
    job = new Job();
    job.type = 'plastic-recycling';
    job.description = 'Kunststoff';
    job.first_start_date = new Date().toISOString();
    job.last_done_date = new Date().toISOString();
    job.status = new JobStatus();
    job.status.state = 0;
    job.price = new Price();
    job.price.value_per_kg = 2;
    job.price.value = 0;
    job.material_id = MaterialId.PE_KUNSTSTOFF_FLASCHEN;
    job.image_name = '' + job.material_id.valueOf() + '.svg';
    job.is_selected = false;
    job.sammelstellen = [];
    jobs.push(job);
    job = new Job();
    job.type = 'pet-recycling';
    job.description = 'PET';
    job.first_start_date = new Date().toISOString();
    job.last_done_date = new Date().toISOString();
    job.status = new JobStatus();
    job.status.state = 0;
    job.price = new Price();
    job.price.value_per_kg = 2;
    job.price.value = 0;
    job.material_id = MaterialId.PET;
    job.image_name = '' + job.material_id.valueOf() + '.svg';
    job.is_selected = false;
    job.sammelstellen = [];
    jobs.push(job);
    job = new Job();
    job.type = 'glassbottle-recycling';
    job.description = 'Glasflaschen';
    job.first_start_date = new Date().toISOString();
    job.last_done_date = new Date().toISOString();
    job.status = new JobStatus();
    job.status.state = 0;
    job.price = new Price();
    job.price.value_per_kg = 1;
    job.price.value = 0;
    job.material_id = MaterialId.GLAS_BOTTLE;
    job.image_name = '' + job.material_id.valueOf() + '.svg';
    job.is_selected = false;
    job.sammelstellen = [];
    jobs.push(job);
    job = new Job();
    job.type = 'generationm-recycling';
    job.description = 'Kunststoffe';
    job.first_start_date = new Date().toISOString();
    job.last_done_date = new Date().toISOString();
    job.status = new JobStatus();
    job.status.state = 0;
    job.price = new Price();
    job.price.value_per_kg = 3;
    job.price.value = 0;
    job.material_id = MaterialId.MIGROS_GENERATION_M;
    job.image_name = '' + job.material_id.valueOf() + '.png';
    job.is_selected = false;
    job.sammelstellen = [];
    jobs.push(job);
    job = new Job();
    job.type = 'carton-recycling';
    job.description = 'Karton';
    job.first_start_date = new Date().toISOString();
    job.last_done_date = new Date().toISOString();
    job.status = new JobStatus();
    job.status.state = 0;
    job.price = new Price();
    job.price.value_per_kg = 1.5;
    job.price.value = 0;
    job.material_id = MaterialId.CARDBOARD;
    job.image_name = '' + job.material_id.valueOf() + '.svg';
    job.is_selected = false;
    job.sammelstellen = [];
    jobs.push(job);
    job = new Job();
    job.type = 'battery-recycling';
    job.description = 'Batterien';
    job.first_start_date = new Date().toISOString();
    job.last_done_date = new Date().toISOString();
    job.status = new JobStatus();
    job.status.state = 0;
    job.price = new Price();
    job.price.value_per_kg = 2.5;
    job.price.value = 0;
    job.material_id = MaterialId.BATTERY;
    job.image_name = '' + job.material_id.valueOf() + '.svg';
    job.is_selected = false;
    job.sammelstellen = [];
    jobs.push(job);
    job = new Job();
    job.type = 'electro-recycling';
    job.description = 'Elektro';
    job.first_start_date = new Date().toISOString();
    job.last_done_date = new Date().toISOString();
    job.status = new JobStatus();
    job.status.state = 0;
    job.price = new Price();
    job.price.value_per_kg = 2.5;
    job.price.value = 0;
    job.material_id = MaterialId.ELECTRIC_HOUSEHOLD;
    job.image_name = '' + job.material_id.valueOf() + '.svg';
    job.is_selected = false;
    job.sammelstellen = [];
    jobs.push(job);
    return jobs;
  }
}
